"""
Patch DataReports.tsx: Fix the Z report supplierBreakdown to use exact promo
matching instead of proportional distribution.
"""

filepath = r'c:\Users\54112\Desktop\GestionPro\components\DataReports.tsx'

with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Replace lines 346-412 (0-indexed 345-411) - the supplierBreakdown IIFE
new_breakdown = [
    "         supplierBreakdown: (() => {\n",
    "            const supplierMap = new Map<string, { gross: number, cost: number }>();\n",
    "\n",
    "            sessionSales.forEach(sale => {\n",
    "               const saleItems = sale.items || [];\n",
    "               const saleItemIds = saleItems.map(i => i.id);\n",
    "\n",
    "               // STEP 1: Resolve supplier for each item and add gross (list price)\n",
    "               const itemsResolved = saleItems.map(item => {\n",
    "                  let supplierName = 'Desconocido';\n",
    "                  if (item.supplierId) {\n",
    "                     const supplier = suppliers.find(s => s.id === item.supplierId);\n",
    "                     if (supplier) supplierName = supplier.name;\n",
    "                  }\n",
    "                  if (supplierName === 'Desconocido') {\n",
    "                     const product = products.find(p => p.id === item.id);\n",
    "                     const bulk = bulkProducts.find(p => p.id === item.id);\n",
    "                     const foundId = product?.supplierId || bulk?.supplierId;\n",
    "                     if (foundId) {\n",
    "                        const supplier = suppliers.find(s => s.id === foundId);\n",
    "                        if (supplier) supplierName = supplier.name;\n",
    "                     }\n",
    "                  }\n",
    "                  return { ...item, supplierName };\n",
    "               });\n",
    "\n",
    "               // Add gross (list price) per supplier\n",
    "               itemsResolved.forEach(item => {\n",
    "                  const itemGross = item.price * item.quantity;\n",
    "                  const itemCost = (item.cost || 0) * item.quantity;\n",
    "                  const current = supplierMap.get(item.supplierName) || { gross: 0, cost: 0 };\n",
    "                  supplierMap.set(item.supplierName, {\n",
    "                     gross: current.gross + itemGross,\n",
    "                     cost: current.cost + itemCost\n",
    "                  });\n",
    "               });\n",
    "\n",
    "               // STEP 2: Detect matched promos and subtract discount from the correct suppliers\n",
    "               if ((sale.discount || 0) > 0 || sale.total < saleItems.reduce((s, i) => s + i.price * i.quantity, 0)) {\n",
    "                  promotions.forEach(promo => {\n",
    "                     if (!promo.active) return;\n",
    "                     const allPresent = promo.triggerProductIds.every(pid => saleItemIds.includes(pid));\n",
    "                     if (!allPresent) return;\n",
    "\n",
    "                     const triggerListTotal = promo.triggerProductIds.reduce((sum, pid) => {\n",
    "                        const item = saleItems.find(i => i.id === pid);\n",
    "                        return sum + (item ? item.price : 0);\n",
    "                     }, 0);\n",
    "                     const promoDiscountAmt = Math.max(0, triggerListTotal - promo.promoPrice);\n",
    "                     if (promoDiscountAmt <= 0) return;\n",
    "\n",
    "                     // Attribute discount to the suppliers whose products are in this promo\n",
    "                     const supplierShares = new Map<string, number>();\n",
    "                     let totalPromoGross = 0;\n",
    "                     promo.triggerProductIds.forEach(pid => {\n",
    "                        const resolved = itemsResolved.find(i => i.id === pid);\n",
    "                        if (resolved) {\n",
    "                           const price = resolved.price;\n",
    "                           totalPromoGross += price;\n",
    "                           supplierShares.set(resolved.supplierName, (supplierShares.get(resolved.supplierName) || 0) + price);\n",
    "                        }\n",
    "                     });\n",
    "\n",
    "                     supplierShares.forEach((share, supName) => {\n",
    "                        const ratio = totalPromoGross > 0 ? share / totalPromoGross : 0;\n",
    "                        const discount = promoDiscountAmt * ratio;\n",
    "                        const current = supplierMap.get(supName) || { gross: 0, cost: 0 };\n",
    "                        supplierMap.set(supName, { gross: current.gross - discount, cost: current.cost });\n",
    "                     });\n",
    "                  });\n",
    "               }\n",
    "\n",
    "               // ADD SURCHARGE TO BREAKDOWN\n",
    "               if ((sale.surcharge || 0) > 0) {\n",
    "                  const surchargeName = 'Recargos / Intereses';\n",
    "                  const currentSurcharge = supplierMap.get(surchargeName) || { gross: 0, cost: 0 };\n",
    "                  supplierMap.set(surchargeName, {\n",
    "                     gross: currentSurcharge.gross + (sale.surcharge || 0),\n",
    "                     cost: currentSurcharge.cost\n",
    "                  });\n",
    "               }\n",
    "            });\n",
    "\n",
    "            const result = Array.from(supplierMap.entries())\n",
    "               .map(([name, data]) => ({\n",
    "                  name,\n",
    "                  gross: data.gross,\n",
    "                  cost: data.cost,\n",
    "                  profit: data.gross - data.cost\n",
    "               }));\n",
    "\n",
    "            return result.sort((a, b) => b.gross - a.gross);\n",
    "         })()\n",
]

# Replace lines 346-412 (0-indexed 345-411)
new_lines = lines[:345] + new_breakdown + lines[412:]

with open(filepath, 'w', encoding='utf-8', newline='') as f:
    f.writelines(new_lines)

print(f"Done! Old: {len(lines)} lines, New: {len(new_lines)} lines")
