"""
Patch DataReports.tsx: Rewrite the per-supplier sidebar calculation
to implement the Hybrid Logic (Option B) for orphaned discounts.
"""

filepath = r'c:\Users\54112\Desktop\GestionPro\components\DataReports.tsx'

with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

start_idx = None
end_idx = None

for i, line in enumerate(lines):
    if "{/* Per-Supplier Summary when filtered */}" in line:
        start_idx = i
    if start_idx is not None and i > start_idx and '})()}' in line:
        end_idx = i + 1
        break

new_sidebar = [
    "                   {/* Per-Supplier Summary when filtered */}\n",
    "                   {supplierFilter !== 'all' && (() => {\n",
    "                      const selSup = suppliers.find(s => s.id === supplierFilter);\n",
    "                      let sCost = 0;\n",
    "                      let sVentaBruta = 0;\n",
    "                      let sPromoDiscount = 0;\n",
    "\n",
    "                      // Helper: check if an item belongs to the selected supplier\n",
    "                      const isSupplierItem = (itemId: string, itemSupplierId?: string) => {\n",
    "                         if (itemSupplierId === supplierFilter) return true;\n",
    "                         const p = products.find(x => x.id === itemId);\n",
    "                         if (p && p.supplierId === supplierFilter) return true;\n",
    "                         const b = bulkProducts.find(x => x.id === itemId);\n",
    "                         if (b && b.supplierId === supplierFilter) return true;\n",
    "                         return false;\n",
    "                      };\n",
    "\n",
    "                      filteredSales.forEach(sale => {\n",
    "                         const saleItems = sale.items || [];\n",
    "                         const ticketGross = saleItems.reduce((sum, i) => sum + (i.price * i.quantity), 0);\n",
    "                         const ticketNet = sale.total - (sale.surcharge || 0);\n",
    "                         const actualTicketDiscount = Math.max(0, ticketGross - ticketNet);\n",
    "\n",
    "                         let supplierGross = 0;\n",
    "                         saleItems.forEach(item => {\n",
    "                            if (isSupplierItem(item.id, item.supplierId)) {\n",
    "                               supplierGross += item.price * item.quantity;\n",
    "                               sCost += (item.cost || 0) * item.quantity;\n",
    "                            }\n",
    "                         });\n",
    "                         sVentaBruta += supplierGross;\n",
    "\n",
    "                         if (actualTicketDiscount > 0 && supplierGross > 0) {\n",
    "                            const cartMap: Record<string, number> = {};\n",
    "                            const pidToSupplier: Record<string, string> = {};\n",
    "                            saleItems.forEach(item => {\n",
    "                               const pid = (item as any).productId || (item as any).product_id || item.id;\n",
    "                               cartMap[pid] = (cartMap[pid] || 0) + item.quantity;\n",
    "                               // resolve supplier for pid\n",
    "                               let itemSup = 'Desconocido';\n",
    "                               if (item.supplierId) itemSup = item.supplierId;\n",
    "                               else {\n",
    "                                  const p = products.find(x => x.id === pid);\n",
    "                                  if (p && p.supplierId) itemSup = p.supplierId;\n",
    "                                  else {\n",
    "                                     const b = bulkProducts.find(x => x.id === pid);\n",
    "                                     if (b && b.supplierId) itemSup = b.supplierId;\n",
    "                                  }\n",
    "                               }\n",
    "                               pidToSupplier[pid] = itemSup;\n",
    "                            });\n",
    "\n",
    "                            const supplierPromoDiscount = new Map<string, number>();\n",
    "                            const sortedPromos = [...promotions].filter(p => p.active).sort((a, b) => (b.promoPrice || 0) - (a.promoPrice || 0));\n",
    "\n",
    "                            for (const promo of sortedPromos) {\n",
    "                               let triggers = promo.triggerProductIds || (promo as any).trigger_product_ids || [];\n",
    "                               if (typeof triggers === 'string') { try { triggers = JSON.parse(triggers) } catch (e) { triggers = [] } }\n",
    "\n",
    "                               let reqs = promo.requirements || [];\n",
    "                               if (typeof reqs === 'string') { try { reqs = JSON.parse(reqs) } catch (e) { reqs = [] } }\n",
    "\n",
    "                               const promoPrice = promo.promoPrice || (promo as any).promo_price || 0;\n",
    "                               const promoType = promo.type || (promo as any).type || 'standard';\n",
    "                               const qtyReq = promo.quantityRequired || (promo as any).quantity_required || 0;\n",
    "\n",
    "                               if (promoType === 'flexible' && qtyReq > 0) {\n",
    "                                  const matchingPids = (triggers as string[]).filter(pid => (cartMap[pid] || 0) > 0);\n",
    "                                  let totalAvailable = matchingPids.reduce((sum, pid) => sum + (cartMap[pid] || 0), 0);\n",
    "                                  const combosPossible = Math.floor(totalAvailable / qtyReq);\n",
    "\n",
    "                                  if (combosPossible > 0) {\n",
    "                                     const availableUnits: { id: string, price: number }[] = [];\n",
    "                                     matchingPids.forEach(pid => {\n",
    "                                        const product = products.find(p => p.id === pid) || bulkProducts.find((p: any) => p.id === pid);\n",
    "                                        const qty = cartMap[pid] || 0;\n",
    "                                        for (let i = 0; i < qty; i++) availableUnits.push({ id: pid, price: (product as any)?.price || 0 });\n",
    "                                     });\n",
    "                                     availableUnits.sort((a, b) => b.price - a.price);\n",
    "\n",
    "                                     const unitsUsed = availableUnits.slice(0, combosPossible * qtyReq);\n",
    "                                     const regularPriceSum = unitsUsed.reduce((sum, u) => sum + u.price, 0);\n",
    "                                     unitsUsed.forEach(u => { if (cartMap[u.id] > 0) cartMap[u.id]--; });\n",
    "\n",
    "                                     const discount = regularPriceSum - (combosPossible * promoPrice);\n",
    "                                     if (discount > 0) {\n",
    "                                        const supId = pidToSupplier[unitsUsed[0]?.id] || 'Desconocido';\n",
    "                                        supplierPromoDiscount.set(supId, (supplierPromoDiscount.get(supId) || 0) + discount);\n",
    "                                     }\n",
    "                                  }\n",
    "                               } else if (promoType === 'weighted' && Array.isArray(reqs) && reqs.length > 0) {\n",
    "                                  let possibleCombos = Infinity;\n",
    "                                  for (const req of reqs) {\n",
    "                                     const minWeight = Number(req.minWeight || 0);\n",
    "                                     const pid = req.productId || req.product_id;\n",
    "                                     const availableWeight = cartMap[pid] || 0;\n",
    "                                     if (availableWeight < minWeight) { possibleCombos = 0; break; }\n",
    "                                     const limit = Math.floor(availableWeight / minWeight);\n",
    "                                     if (limit < possibleCombos) possibleCombos = limit;\n",
    "                                  }\n",
    "                                  if (possibleCombos === Infinity) possibleCombos = 0;\n",
    "\n",
    "                                  if (possibleCombos > 0) {\n",
    "                                     let regularPricePerCombo = 0;\n",
    "                                     reqs.forEach((req: any) => {\n",
    "                                        const minWeight = Number(req.minWeight || 0);\n",
    "                                        const pid = req.productId || req.product_id;\n",
    "                                        const product = products.find(p => p.id === pid) || bulkProducts.find((p: any) => p.id === pid);\n",
    "                                        const pricePerKg = (product as any)?.price || (product as any)?.pricePerKg || 0;\n",
    "                                        regularPricePerCombo += (minWeight * pricePerKg);\n",
    "                                        cartMap[pid] -= (possibleCombos * minWeight);\n",
    "                                     });\n",
    "                                     const savingsPerCombo = regularPricePerCombo - promoPrice;\n",
    "                                     if (savingsPerCombo > 0) {\n",
    "                                        const firstPid = (reqs[0] as any)?.productId || (reqs[0] as any)?.product_id;\n",
    "                                        const supId = pidToSupplier[firstPid] || 'Desconocido';\n",
    "                                        supplierPromoDiscount.set(supId, (supplierPromoDiscount.get(supId) || 0) + (savingsPerCombo * possibleCombos));\n",
    "                                     }\n",
    "                                  }\n",
    "                               } else {\n",
    "                                  const requirements: Record<string, number> = {};\n",
    "                                  (triggers as string[]).forEach((pid: string) => {\n",
    "                                     requirements[pid] = (requirements[pid] || 0) + 1;\n",
    "                                  });\n",
    "                                  while (true) {\n",
    "                                     const canApply = Object.entries(requirements).every(([pid, req]) => (cartMap[pid] || 0) >= req);\n",
    "                                     if (!canApply) break;\n",
    "                                     Object.entries(requirements).forEach(([pid, req]) => { cartMap[pid] -= req; });\n",
    "                                     const regularSum = (triggers as string[]).reduce((sum, pid) => {\n",
    "                                        const p = products.find(prod => prod.id === pid) || bulkProducts.find((prod: any) => prod.id === pid);\n",
    "                                        return sum + ((p as any)?.price || 0);\n",
    "                                     }, 0);\n",
    "                                     const discount = regularSum - promoPrice;\n",
    "                                     if (discount > 0) {\n",
    "                                        const supId = pidToSupplier[(triggers as string[])[0]] || 'Desconocido';\n",
    "                                        supplierPromoDiscount.set(supId, (supplierPromoDiscount.get(supId) || 0) + discount);\n",
    "                                     }\n",
    "                                  }\n",
    "                               }\n",
    "                            }\n",
    "\n",
    "                            let totalDetectedDiscount = 0;\n",
    "                            supplierPromoDiscount.forEach(d => totalDetectedDiscount += d);\n",
    "\n",
    "                            // Attribute to selected supplier\n",
    "                            const baseDetectedForSupplier = supplierPromoDiscount.get(supplierFilter) || 0;\n",
    "                            let finalSupplierDiscount = baseDetectedForSupplier;\n",
    "\n",
    "                            if (totalDetectedDiscount > 0 && totalDetectedDiscount < actualTicketDiscount) {\n",
    "                               // Distribute remainder ONLY among suppliers who had a promo detected (Option B)\n",
    "                               const remainder = actualTicketDiscount - totalDetectedDiscount;\n",
    "                               const ratio = baseDetectedForSupplier / totalDetectedDiscount;\n",
    "                               finalSupplierDiscount += remainder * ratio;\n",
    "                            } else if (totalDetectedDiscount > actualTicketDiscount) {\n",
    "                               // Cap if engine overcalculated\n",
    "                               const scaleFactor = actualTicketDiscount / totalDetectedDiscount;\n",
    "                               finalSupplierDiscount = baseDetectedForSupplier * scaleFactor;\n",
    "                            }\n",
    "                            // NOTE: If totalDetectedDiscount === 0, it's an orphaned discount. Option B: We don't deduct it from any supplier.\n",
    "\n",
    "                            sPromoDiscount += finalSupplierDiscount;\n",
    "                         }\n",
    "                      });\n",
    "\n",
    "                      const sVentaNeta = sVentaBruta - sPromoDiscount;\n",
    "                      return (\n",
    "                         <div className=\"mt-3 space-y-2\">\n",
    "                            <div className=\"bg-blue-50 px-3 py-2 rounded-lg border border-blue-100\">\n",
    "                               <p className=\"text-[10px] text-blue-600 font-bold uppercase\">Costo {selSup?.name}</p>\n",
    "                               <p className=\"text-lg font-bold text-blue-700\">${Math.round(sCost).toLocaleString('es-AR')}</p>\n",
    "                            </div>\n",
    "                            <div className=\"bg-green-50 px-3 py-2 rounded-lg border border-green-100\">\n",
    "                               <p className=\"text-[10px] text-green-600 font-bold uppercase\">Venta Bruta {selSup?.name}</p>\n",
    "                               <p className=\"text-lg font-bold text-green-700\">${Math.round(sVentaBruta).toLocaleString('es-AR')}</p>\n",
    "                            </div>\n",
    "                            {sPromoDiscount > 0 && (\n",
    "                               <div className=\"bg-red-50 px-3 py-2 rounded-lg border border-red-100\">\n",
    "                                  <p className=\"text-[10px] text-red-600 font-bold uppercase\">Desc. Promos {selSup?.name}</p>\n",
    "                                  <p className=\"text-lg font-bold text-red-600\">-${Math.round(sPromoDiscount).toLocaleString('es-AR')}</p>\n",
    "                               </div>\n",
    "                            )}\n",
    "                            <div className=\"bg-purple-50 px-3 py-2 rounded-lg border border-purple-100\">\n",
    "                               <p className=\"text-[10px] text-purple-600 font-bold uppercase\">Venta Neta {selSup?.name}</p>\n",
    "                               <p className=\"text-lg font-bold text-purple-700\">${Math.round(sVentaNeta).toLocaleString('es-AR')}</p>\n",
    "                            </div>\n",
    "                            <div className=\"bg-amber-50 px-3 py-2 rounded-lg border border-amber-100\">\n",
    "                               <p className=\"text-[10px] text-amber-600 font-bold uppercase\">Ganancia Neta {selSup?.name}</p>\n",
    "                               <p className=\"text-lg font-bold text-amber-700\">${Math.round(sVentaNeta - sCost).toLocaleString('es-AR')}</p>\n",
    "                            </div>\n",
    "                         </div>\n",
    "                      );\n",
    "                   })()}\n"
]

new_lines = lines[:start_idx] + new_sidebar + lines[end_idx:]

with open(filepath, 'w', encoding='utf-8', newline='') as f:
    f.writelines(new_lines)

print(f"Patched sidebar supplier logic. Old size: {len(lines)}, new: {len(new_lines)}")
